= Kotlin Domain Driven Design (KDDD)
Tepex <tepex@mail.ru>
1.0, 15/II-2026
:source-highliter: rouge

Методология и инструментарий для концептуального проектирования и реализации формальной системы типов и моделей предметных областей (Domain) на языке Котлин в соответствии с DDD.

== О проекте
https://itarchdev.github.io/kddd/[Документация]

== Структура проекта
. link:fts/[fts] — Библиотека, которая содержит базовые типы и функции для создания формальных систем типов и моделей предметных областей.
. link:ksp-processor/[ksp-processor] — Кодогенератор, который обрабатывает аннотации в коде и генерирует дополнительные
. link:docs/[docs] — Документация, примеры использования и учебные материалы по методологии KDDD.

== Workflow
link:.github/workflows/pr-check.yml[Проверка сборки (build & test)] для обычных _PR_, чтобы гарантировать работоспособность кода до его попадания в `dev`.

link:.github/workflows/release-modules.yml[_Release Please_ workflow]:

. Вы пушите в `dev`: обычный комит вида `feat(fts): add core logic`.
. `release-please` (Шаг 1): Видит новый комит, создает новый _PR_ (или обновляет существующий), который содержит:
.. Обновленный `.release-please-manifest.json` с версией `1.1.0`.
.. Обновленный `fts/CHANGELOG.md`.
. Вы мержите этот _PR_: После проверки вы нажимаете "Merge".
. `release-please` (Шаг 2): Снова запускается по пушу в `dev`. Понимает, что это мерж его собственного _PR_, создает _GitHub Release_ и _Git Tag_ (fts-v1.1.0).
. `publish`: Видит флаг `releases_created: true`, считывает обновленный манифест через Gradle и отправляет артефакт в _Maven Central_.
. `smoke-test`: После публикации запускает тесты, которые проверяют, что опубликованная версия доступна в _Maven Central_ и может быть использована в проекте.
. `sync-to-main`: После успеха `publish`, скрипт берет актуальное состояние `dev` (уже с новыми версиями и `CHANGELOG`) и переносит его в `main`.
. Игнорирование пустых релизов: Если вы замержите коммит без _scope_ или просто `docs:`, _Release Please_ не создаст _PR_ и публикация не запустится.

== Установка
=== Библиотека FTS
image:https://img.shields.io/maven-central/v/ru.it-arch.kddd/fts[Maven Central Version]

[source,kotlin]
----
dependencies {
    implementation("ru.it-arch.kddd:fts:<latest_version>")
}
----

=== Кодогенератор
[source,kotlin]
----
dependencies {
    ksp("ru.it-arch.kddd:ksp-processor:<latest_version>")
}
----

=== Документация
Генерируется с помощью https://jekyllrb.com[Jekyll]. Для локального запуска необходимо установить Ruby v3.3 и в директории link:docs/[docs] выполнить:
[source,bash]
----
$ bundle install
$ bundle exec jekyll serve --baseurl /kddd
----

Открыть http://localhost:4000/kddd/[http://localhost:4000/kddd/] в браузере, чтобы просмотреть документацию.
