= Методология моделирования предметной области на языке Котлин
Tepex <tepex@mail.ru>
1.0, 16/II-2026
:source-highliter: rouge

Аннотация этого документа.

== Введение
Сложное корпоративное ПО, информационные системы (ИС), рассчитанные на долгосрочное существование,

== Потребность
Описание болей. Причины их появления (сложность, много связей, скорость изменения требований)

=== Требования к доменной модели предметной области

- быть адаптивным
- простым — минимизация связей и зависимостей между компонентами
- обособленность компонентов, модульность
- наличие формальной системы типов и DSL на ее основе в рамках которого определяется функционал.
- минимизация вариативности: ограниченность, иммутабельность, контроль над изменениями, детерминированным предсказуемым поведением
- минимизация внешних зависимостей и побочных эффектов
- валидация на этапе создания объектов и защита инвариантности
- покрытие юнит-тестами логики модели предметной области на концептуальном уровне
- вендор-лок

=== Требования к реализации на языке Котлин
- Создаваемая ФСТ предметной области должна наследоваться от типов, определенных в библиотеке fst.
- отсутствие _Primitive Obsession_. Допускаются исключения.
- Иммутабельность публичных свойств
- Приватность конструкторов. Создание объектов через DSL-билдеры или копирование с изменением с предварительной валидацией входных параметров
- Разделение абстракции и имплементации. Допускаются исключения для простых случаев.
- Типы полей структур данных задаются как внутренние типы если не носят общего характера для домена.
- Разделение структуры и поведения. Поведение задается с помощью функций-расширений.
